# Generated by Django 3.0.7 on 2020-09-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20200925_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c_tudent',
            new_name='student',
        ),
    ]
