class A:
         def myfun(self):
                  return "Vijay"
class B(A):
         def myfun2(self):
                  return self.myfun()
class C:
         def myfun(self):
                  return "Vijay"
class D:
         def myfun(self):
                  return "Vijay"
