# Generated by Django 3.0.7 on 2020-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phno',
            field=models.IntegerField(null=True),
        ),
    ]
