# Generated by Django 3.0.7 on 2020-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('f_age', models.IntegerField()),
                ('f_empid', models.IntegerField()),
                ('f_phno', models.IntegerField()),
                ('f_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
