# Generated by Django 3.0.7 on 2020-09-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='c_tudent',
        ),
    ]
